#define _GNU_SOURCE
#include "dsasm_vocoder_graph.h"
#include <errno.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

static double now_ms(void){struct timespec ts;clock_gettime(CLOCK_MONOTONIC_RAW,&ts);return 1000.0*ts.tv_sec+1e-6*ts.tv_nsec;}
static float *read_f32(const char*p,size_t n){FILE*f=fopen(p,"rb");if(!f)return NULL;float*x=malloc(n*sizeof(float));if(!x){fclose(f);return NULL;}size_t k=fread(x,sizeof(float),n,f);fclose(f);if(k!=n){free(x);return NULL;}return x;}
static int write_f32(const char*p,const float*x,size_t n){FILE*f=fopen(p,"wb");if(!f)return-1;int rc=fwrite(x,sizeof(float),n,f)==n?0:-1;fclose(f);return rc;}
static int write_wav(const char*p,const float*x,size_t n,unsigned sr){FILE*f=fopen(p,"wb");if(!f)return-1;uint32_t bytes=(uint32_t)(n*2),riff=36+bytes;uint16_t one=1,bits=16;fwrite("RIFF",1,4,f);fwrite(&riff,4,1,f);fwrite("WAVEfmt ",1,8,f);uint32_t sz=16;fwrite(&sz,4,1,f);fwrite(&one,2,1,f);fwrite(&one,2,1,f);fwrite(&sr,4,1,f);uint32_t br=sr*2;uint16_t ba=2;fwrite(&br,4,1,f);fwrite(&ba,2,1,f);fwrite(&bits,2,1,f);fwrite("data",1,4,f);fwrite(&bytes,4,1,f);for(size_t i=0;i<n;i++){float v=x[i];if(v>1)v=1;if(v<-1)v=-1;int16_t s=(int16_t)lrintf(v*32767.0f);fwrite(&s,2,1,f);}fclose(f);return 0;}
static int cmpf(const float*a,const float*b,size_t n){double ss=0,sa=0,sb=0,dot=0;float ma=0;for(size_t i=0;i<n;i++){float d=fabsf(a[i]-b[i]);if(d>ma)ma=d;ss+=(double)d*d;sa+=(double)a[i]*a[i];sb+=(double)b[i]*b[i];dot+=(double)a[i]*b[i];}double rmse=sqrt(ss/n),co=dot/(sqrt(sa*sb)+1e-30),snr=10.0*log10((sb+1e-30)/(ss+1e-30));float tol=5e-3f;const char*e=getenv("DSASM_GOLDEN_TOL");if(e){float v=strtof(e,NULL);if(v>0)tol=v;}const char*ce=getenv("DSASM_GOLDEN_COS"),*se=getenv("DSASM_GOLDEN_SNR");if(ce||se){double cmin=ce?strtod(ce,NULL):0.0,smin=se?strtod(se,NULL):-1e30;printf("  parity max_abs=%.9g rmse=%.9g cosine=%.9g SNR=%.2f dB gate=(cos>=%.6g,SNR>=%.2f)\n",ma,rmse,co,snr,cmin,smin);return (co>=cmin&&snr>=smin)?0:1;}printf("  parity max_abs=%.9g rmse=%.9g cosine=%.9g SNR=%.2f dB tol=%.4g\n",ma,rmse,co,snr,tol);return ma<tol?0:1;}
static int cmpdbl(const void*a,const void*b){double x=*(const double*)a,y=*(const double*)b;return(x>y)-(x<y);}
int main(int argc,char**argv){
 if(argc<3){fprintf(stderr,"usage: %s inspect MODEL.dsv35 | infer MODEL.dsv35 --mel mel.f32 --f0 f0.f32 --out wave.f32 [--wav out.wav] [--golden g.f32] [--workers N] [--rounds N] [--profile]\n",argv[0]);return 2;}
 if(!strcmp(argv[1],"inspect")){DSAsmVocoderGraph*g=ds_vocoder_graph_load(argv[2],1);if(!g){perror("load");return 1;}printf("DSVOC35: frames=%zu mel_bins=%zu samples=%zu\n",ds_vocoder_graph_frames(g),ds_vocoder_graph_mel_bins(g),ds_vocoder_graph_samples(g));ds_vocoder_graph_free(g);return 0;}
 if(strcmp(argv[1],"infer")){fprintf(stderr,"unknown command\n");return 2;}const char*melp=NULL,*f0p=NULL,*outp=NULL,*wavp=NULL,*goldp=NULL;size_t workers=8,rounds=3;int profile=0;
 for(int i=3;i<argc;i++){if(!strcmp(argv[i],"--mel")&&i+1<argc)melp=argv[++i];else if(!strcmp(argv[i],"--f0")&&i+1<argc)f0p=argv[++i];else if(!strcmp(argv[i],"--out")&&i+1<argc)outp=argv[++i];else if(!strcmp(argv[i],"--wav")&&i+1<argc)wavp=argv[++i];else if(!strcmp(argv[i],"--golden")&&i+1<argc)goldp=argv[++i];else if(!strcmp(argv[i],"--workers")&&i+1<argc)workers=strtoul(argv[++i],0,10);else if(!strcmp(argv[i],"--rounds")&&i+1<argc)rounds=strtoul(argv[++i],0,10);else if(!strcmp(argv[i],"--profile"))profile=1;else{fprintf(stderr,"bad arg %s\n",argv[i]);return 2;}}
 if(!melp||!f0p||!outp){fprintf(stderr,"--mel --f0 --out required\n");return 2;}DSAsmVocoderGraph*g=ds_vocoder_graph_load(argv[2],workers);if(!g){fprintf(stderr,"failed to load bundle\n");return 1;}size_t T=ds_vocoder_graph_frames(g),M=ds_vocoder_graph_mel_bins(g),N=ds_vocoder_graph_samples(g);float*mel=read_f32(melp,T*M),*f0=read_f32(f0p,T),*wave=malloc(N*sizeof(float));if(!mel||!f0||!wave){fprintf(stderr,"input read/alloc failed\n");return 1;}double*ts=malloc(rounds*sizeof(double));for(size_t r=0;r<rounds;r++){double a=now_ms();int rc=ds_vocoder_graph_infer(g,mel,f0,wave,profile&&r==rounds-1);ts[r]=now_ms()-a;if(rc){fprintf(stderr,"infer rc=%d\n",rc);return 1;}}qsort(ts,rounds,sizeof(double),cmpdbl);double med=ts[rounds/2],dur=1000.0*N/44100.0;printf("DSASM PURE-ASM vocoder: frames=%zu samples=%zu workers=%zu median=%.3f ms audio=%.3f ms RTF=%.3f speed=%.3fx\n",T,N,ds_vocoder_graph_workers(g),med,dur,med/dur,dur/med);write_f32(outp,wave,N);if(wavp)write_wav(wavp,wave,N,44100);if(goldp){float*gold=read_f32(goldp,N);if(!gold){fprintf(stderr,"golden read failed\n");return 1;}int bad=cmpf(wave,gold,N);free(gold);if(bad){fprintf(stderr,"DSASM parity FAIL\n");return 1;}puts("DSASM parity: OK");}free(ts);free(wave);free(f0);free(mel);ds_vocoder_graph_free(g);return 0;
}
